### ISSUE TITLE
Identify application components

### ISSUE THREAD

**Issue by markmishaevcx** [applicationdesignframework/applicationdesignframework.github.io#1]
Can you provide more information about establishing component boundaries and integration interfaces?

You were mentioning:
1.  Business Domain Bounded Context
2.  Regulatory Compliance 
3. Change Cadence
4. Team Location 
5. Risk 
6. Performance Isolation
7. Technology
8. User Personas

I'd like us to take real-word scenarios/examples of how to break it down by one or more of those dimensions.

WDYT?

**Comment by alexpulver** [comment]
Thanks for reading and opening the first issue 😄! Do you mean adding a collection of examples for this? For an example, let's take a system that processes credit card transactions. That system needs to store credit card details. Most of the system can use that data in tokenized format (e.g. for fraud prevention). Hence, one could break down the system into (at least) two components based on regulatory compliance fracture plane: 1/ accessing full credit card data 2/ the rest. Something like that?

**Comment by markmishaevcx** [comment]
Yes, something like that, probably show some systematic approach of taking system requirements and breaking it down based on the aspects mentioned above.

**Comment by alexpulver** [comment]
Thanks! I am now working with a colleague on a reference implementation for a blog post, and we are using ADF there. Once done, that can be the first full example. I will update here on progress 🙂.

**Comment by alexpulver** [comment]
@markmishaevcx I added an [end-to-end example](https://github.com/alexpulver/adf/tree/main/examples/documentsapp) that includes an architectural decision record (ADR) for [component boundaries](https://github.com/alexpulver/adf/tree/main/examples/documentsapp#application). I tried to make the example somewhat simple, hopefully with just enough detail to showcase the approach and not more. Would be glad to have your feedback on this 🙏.

**Comment by alexpulver** [comment]
Hey @markmishaevcx, I added yet another example for application boundary evolution and updated the content of the first example. Closing this for now, please re-open if you think a further discussion might be helpful. Thanks!

Examples:
- [High-level application design from use case to code](https://github.com/applicationdesignframework/applicationdesignframework.github.io/blob/main/examples/application-design/README.md)
- [Application boundary and deployment model evolution](https://github.com/applicationdesignframework/applicationdesignframework.github.io/blob/main/examples/application-evolution/README.md)
