### ISSUE TITLE
[Feat] - Define application hierarchy 

### ISSUE THREAD

**Issue by tsahiduek** [applicationdesignframework/applicationdesignframework.github.io#2]
I would like to suggest defining hierarchy between applications designed based on ADF, in a way that implies that a component  can (or even should) be an application (with its own design based on ADF)
This is an hierarchical example of a "Trivia Game" company:

 Trivia Game (Application )
-->Landing Zone (Application)
----> DNS Configuration (Application) 
----> Amazon EKS Cluster (Application)
--------> Compute management (Logical Unit)
--------> Kubernetes Add-Ons (Logical Unit)
--------> Team and Access Management (Logical Unit)
--------> Payments Backend Runtime Code (Logical Unit) 
--------> Image  Processing Runtime Code (Logical Unit) 
--> Payments Backend (Application)
----> Payments Backend Load Balancer (Logical Unit) 
----> Payments Backend Runtime Code (Logical Unit) 
----> Payments Backend Database (Logical Unit)

**Comment by alexpulver** [comment]
@tsahiduek thanks! This is something to think through. Let's consider the following use cases: 1/ application with zero components (e.g. chatbot) 2/ application with two components, front-end and back-end, where each has a dedicated repository and pipeline. Here, both the application and component are deployment units. For example, a builder can deploy each of those (chatbot, front-end, back-end) as a separate CloudFormation stack. I'd need to think how would we represent these.

Also, AWS Well-Architected Framework has the following [definitions](https://docs.aws.amazon.com/wellarchitected/latest/framework/definitions.html):
* A **component** is the code, configuration, and AWS Resources that together deliver against a requirement. A component is often the unit of technical ownership, and is decoupled from other components.
* The term **workload** is used to identify a set of components that together deliver business value. A workload is usually the level of detail that business and technology leaders communicate about.
* We think about **architecture** as being how components work together in a workload. How components communicate and interact is often the focus of architecture diagrams.
* Within an organization the **technology portfolio** is the collection of workloads that are required for the business to operate.

Perhaps we should always use the application terminology at all levels (like you suggested above), and allow to [optionally?] add application type dimension with technology portfolio, workload, or component as values/ Chatbot application would be workload, whereas front-end and back-end applications would be component.

Also, I think we should consider whether version control and toolchain/pipeline impact how we think about organizing applications.
