### ISSUE TITLE
Add template(s)

### ISSUE THREAD

**Issue by szukalski** [applicationdesignframework/applicationdesignframework.github.io#3]
Templates for this approach would be really useful to guide users through the process.

Dividing these into different stakeholder views would help clarify who would be working on which part.

Ie. Business/Product owner would be creating use cases, stories, and requirements. Engineering would be responsible for later stages to realise these.

These views would separate between service experience, versus how to realise said experience.

**Comment by alexpulver** [comment]
@szukalski thanks for submitting the issue and for the suggestions! Adding stakeholders is a great idea - will do 🙏 . Myself and @itsmanu are working on an end-to-end ADF example (will add to this repo when done). We will think about how to create a template from it.

**Comment by alexpulver** [comment]
@szukalski added the personas and [the example](https://github.com/alexpulver/adf/tree/main/examples/documentsapp). The example can be a starting point for others. I'd like to see whether/how people use this example, and then see if a specific template might be of use. Thanks!
